pima_indians:
  cuda: True
  num_iter: 20
  data:
    dataset: "pima_indians"
    training: 567
    validating: 100
    testing: 100
  level1:
    eta: 1.
    stochastic: 1.
    size_in: 8
    size_out: 10
    plot: True
    type: "kpca"
    constraint: "soft"
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 567
    kernel:
      kernel_type: "rbf"
      sigma: 3.
      sigma_trainable: True
  level2:
    eta: 1.
    stochastic: 1
    size_in: 10
    size_out: 10
    plot: True
    type: "kpca"
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 567
    kernel:
      kernel_type: "rbf"
      sigma: 1.
      sigma_trainable: True
  level3:
    eta: 1.
    stochastic: 1
    size_in: 10
    size_out: 1
    plot: True
    type: "lssvm"
    gamma: 1.
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 567
    kernel:
      kernel_type: "rbf"
      sigma: 1.
      sigma_trainable: True
  opt:
    type: sgd
    maxiter: 1.e+5
    kernel_rate: 10
    tol: 0
    lr: 5.e-3
    epoch: 200
    early_stopping: 5
