# coding=utf-8
from .Kernel import Kernel as Kernel
from .Implicit import Implicit as Implicit
from .Explicit import Explicit as Explicit
from .Exponential import Exponential as Exponential
from .Linear import Linear as Linear
from .RBF import RBF as RBF
from .RFF import RFF as RFF
from .Laplacian import Laplacian as Laplacian
from .Cosine import Cosine as Cosine
from .Hat import Hat as Hat
from .Sigmoid import Sigmoid as Sigmoid
from .Indicator import Indicator as Indicator
from .Nystrom import Nystrom as Nystrom
from .Polynomial import Polynomial as Polynomial
from .ExplicitNN import ExplicitNN as ExplicitNN
from .ImplicitNN import ImplicitNN as ImplicitNN
from .AdditiveChi2 import AdditiveChi2 as AdditiveChi2
from .SkewedChi2 import SkewedChi2 as SkewedChi2
from .RandomFeatures import RandomFeatures as RandomFeatures
from .factory import factory as factory