# coding=utf-8
from .kernel import Kernel as Kernel
from .implicit import Implicit as Implicit
from .explicit import Explicit as Explicit
from .exponential import Exponential as Exponential
from .linear import Linear as Linear
from .rbf import RBF as RBF
from .rff import RFF as RFF
from .laplacian import Laplacian as Laplacian
from .cosine import Cosine as Cosine
from .hat import Hat as Hat
from .sigmoid import Sigmoid as Sigmoid
from .indicator import Indicator as Indicator
from .nystrom import Nystrom as Nystrom
from .polynomial import Polynomial as Polynomial
from .explicit_nn import ExplicitNN as ExplicitNN
from .implicit_nn import ImplicitNN as ImplicitNN
from .additive_chi_2 import AdditiveChi2 as AdditiveChi2
from .skewed_chi_2 import SkewedChi2 as SkewedChi2
from .random_features import RandomFeatures as RandomFeatures
from .factory import factory as factory