wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1670345970.195749
    t:
      1:
      - 1
      - 30
      - 55
      3:
      - 23
      4: 3.10.4
      5: 0.13.5
      8:
      - 5
