pid:
  cuda: True
  num_iter: 20
  data:
    dataset: "pid"
    training: 400
    validating: 112
    testing: 255
  level1:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 3
  level2:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 3
  level3:
    eta: 3
    gamma: 5
    size_out: 1
    type: "lssvm"
    classifier: False
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  opt:
    type: sgd
    init: True
    batches: 1
    early_stopping: 200
    maxiter: 1.e+5
    lr: 0.005
    kernel_rate: 5
    stochastic: 1.
    tol: 0
    epoch: 250
    reduce_epochs: 7500

ion:
  cuda: True
  num_iter: 20
  data:
    dataset: "ion"
    training: 170
    validating: 64
    testing: 116
  level1:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 6.
  level2:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 3.
  level3:
    size_out: 1
    type: "lssvm"
    classifier: False
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  opt:
    type: sgd
    init: True
    batches: 1
    early_stopping: 200
    maxiter: 1.e+5
    lr: 0.01
    kernel_rate: 5
    stochastic: 1.
    tol: 1.e-9
    epoch: 250
    reduce_epochs: 7500
    reduce_rate: 2


bld:
  cuda: True
  num_iter: 20
  data:
    dataset: "bld"
    training: 170
    validating: 60
    testing: 114
  level1:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 2
  level2:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  level3:
    size_out: 1
    type: "lssvm"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  opt:
    lr: 0.005
    kernel_rate: 20


adult:
  cuda: True
  num_iter: 20
  data:
    dataset: "adult"
    training: 5000
    validating: 500
    testing: 500
  level1:
    size_out: 20
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
      sigma: 7
  level2:
    size_out: 10
    type: "kpca"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  level3:
    size_out: 1
    type: "lssvm"
    kernel:
      kernel_type: "rbf"
      sigma_trainable: True
  opt:
    init: False
    batches: 100
    early_stopping: 10000
    maxiter: 10000
    lr: 0.005
    kernel_rate: 20
    stochastic: .01