pima_indians:
  cuda: True
  data:
    dataset: "pima_indians"
    n_samples: 400
  level1:
    eta: 1.
    stochastic: 1.
    size_in: 8
    size_out: 20
    plot: True
    type: "kpca"
    constraint: "soft"
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 400
    kernel:
      kernel_type: "rbf"
      sigma: 3.
      sigma_trainable: True
  level2:
    eta: 1.
    stochastic: 1
    size_in: 20
    size_out: 20
    plot: True
    type: "kpca"
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 400
    kernel:
      kernel_type: "rbf"
      sigma: 1.
      sigma_trainable: True
  level3:
    eta: 1.
    stochastic: 1
    size_in: 20
    size_out: 1
    plot: True
    type: "lssvm"
    gamma: 1
    representation: "dual"
    points_trainable: False
    aggregate: False
    init_kernels: 400
    kernel:
      kernel_type: "rbf"
      sigma: 1.
      sigma_trainable: True
  opt:
    type: sgd
    maxiter: 1.e+4
    kernel_rate: 2
    tol: 0
    lr: 1.e-2
    step: 200
